name: final_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  glass: ^1.0.2+1
  supabase_flutter: ^2.0.2
  crystal_navigation_bar: ^1.0.0
  dot_navigation_bar: ^1.0.2
  icons_plus: ^5.0.0
  image_picker: ^1.0.5
  toggle_switch: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/image