name: final_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  glass: ^1.0.2+1
  http: ^1.1.2
  supabase_flutter: ^2.0.2
  crystal_navigation_bar: ^1.0.0
  dot_navigation_bar: ^1.0.2
  carousel_slider: ^4.2.1
  icons_plus: ^5.0.0
  image_picker: ^1.0.5
  toggle_switch: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.0.9
  intl:
  flutter_svg: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/static/Cairo-Light.ttf
          weight: 200
        - asset: assets/static/Cairo-Regular.ttf
        - asset: assets/static/Cairo-Medium.ttf
          weight: 500
        - asset: assets/static/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/static/Cairo-Bold.ttf
          weight: 700
        - asset: assets/static/Cairo-Black.ttf
          weight: 800